### PR TITLE
added gitlab and bitbucket to social

### PR DESCRIPTION
**Pull request by dasari810**
-  added GitLab and Bitbucket to social icons 
- Created ```_gitlab.less``` and ```_bitbucket.less```  file and added the button to website via ```assets/js/button-examples.js```
 

Issue: #936

### CODE REVIEW

**Comment by dsnehasish74** [comment]
ok I think it's ok . @shahednasser please review this and @dasari810 thank u for your work

**Comment by shahednasser** [comment]
Great work thanks!

@all-contributors please add @dasari810 for code

**Comment by shahednasser** [comment]
@all-contributors please add @dsnehasish74 for idea

**Comment by shahednasser** [comment]
Hi @dsnehasish74 thank you for reviewing this PR and the issue related to it. I will be sending you an invite to join this organization as a reviewer and I hope you accept it!

**Comment by dsnehasish74** [comment]
@shahednasser thank you for inviting me .

**Pull request merged**
