### PR TITLE
setting button is modified

### PR DESCRIPTION
**Pull request by arkumari2000**
removed `position:absolute` in file `src/components/icon/_setting.less` 

Issue: #689

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Please run `npm run compile` and commit the changes

**Comment by arkumari2000** [comment]
> Please run `npm run compile` and commit the changes

I did only `npm start`. Okay, I will do `npm run compile` also.

**Comment by arkumari2000** [comment]
please review now.
Thanks

**Comment by shahednasser** [comment]
Great thank you!

@all-contributors please add @arkumari2000 for code and bug

**Pull request merged**
