### PR TITLE
Website Revamp

### PR DESCRIPTION
**Pull request by HADES-01**
## Website Revamp

In the new and enhanced version of the SButtons website following changes have been made:

1. Created a new header with a new and modern design.  
2. Separated basic, rounded and block buttons with tabbed navigation.
3. Created a landing page with only required information.

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
It all looks great you've done an amazing job! I just have one request which is can you rename the pages `index.html` to `examples.html` and `getStarted.html` to `documentation.html`? That way it will match the new structure of the website as well.

**Comment by HADES-01** [comment]
@shahednasser Should I also change the new `home.html` to `index.html`, so that it is the landing page of the website?

**Review by shahednasser — CHANGES_REQUESTED** [review]
Ok all looks good just change the links in the navbar

**Comment by shahednasser** [comment]
Thank you so much @HADES-01 ! You've done a wonderful job with this.

@chaitanya4vedi please check out @HADES-01 work as you will need to make the Footer and Sidebar complement his work.

Thank you both you're helping out a lot.

**Comment by chaitanya4vedi** [comment]
@HADES-01 Amazing Work dude! It looks very nice.

**Comment by chaitanya4vedi** [comment]
@shahednasser I am sorry to say but I am not able to do the task as of now. My laptop had some issues for some days and yesterday it stopped working. So I called for an onsite repair. I don't know how much time will it take. If you want you can assign it to someone or else I will do it as soon as my laptop gets repaired.

**Comment by shahednasser** [comment]
@chaitanya4vedi thank you for letting me know and I hope your laptop gets fixed soon!

@HADES-01 would you like to work on the rest of the website or would you rather someone else do it? I have someone in mind who might be able to help but as you have worked on a big part of it I thought I'd check with you first. Please let me know.

**Comment by HADES-01** [comment]
@shahednasser I'm fine with either way you want to go.

**Comment by shahednasser** [comment]
@HADES-01 I actually prefer you do it since you already have done a great job at it, but I want to leave it up to you to decide.

**Comment by HADES-01** [comment]
@shahednasser Sure, I'd be more than happy to do it.

**Comment by shahednasser** [comment]
Then please go ahead!

**Pull request merged**
