### PR TITLE
Atom button

### PR DESCRIPTION
**Pull request by harjotkarwal**
Added animated button.
 Referred to issue #918

Issue:

### CODE REVIEW

**Comment by harjotkarwal** [comment]
@shahednasser Have a look at my PR.

**Review by HeinKhantZaw — APPROVED** [review]

**Review by shahednasser — CHANGES_REQUESTED** [review]
Thank you for your work @harjotkarwal . I think the "atom" that appears on hover should be white in the middle. Also, instead of using Lato please remove it and instead use "Syne" in `asset/css/index.css`. We only use fonts if it's absolutely necessary for the button's style.

**Comment by harjotkarwal** [comment]
> 
> 
> Thank you for your work @harjotkarwal . I think the "atom" that appears on hover should be white in the middle. Also, instead of using Lato please remove it and instead use "Syne" in `asset/css/index.css`. We only use fonts if it's absolutely necessary for the button's style.

Updated.

**Comment by shahednasser** [comment]
Great work thank you!

@all-contributors please add @harjotkarwal for code

**Pull request merged**
