### PR TITLE
Added a animated class to 'Transparent On Hover' Button

### PR DESCRIPTION
**Pull request by ChristopherMarques**
I've added a new "animated class" to an animated button named as "Transparent On Hover"

Issue: #1022

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Hello @ChristopherMarques sorry for the delay and thank you for your work. Can you please remove all changes in package-lock.json?

**Review by shahednasser — CHANGES_REQUESTED** [review]
There are still changes in package-lock.json, so I suggest you copy the content of the file from our repository then committing it. That way it will remove any changes made to it.

**Comment by ChristopherMarques** [comment]
Sorry, now i've copied exactly the package-lock.json of the official repository, I believe that the problem is solved. 😀

**Comment by shahednasser** [comment]
Thank you for your work!

@all-contributors please add @ChristopherMarques for code

**Comment by ChristopherMarques** [comment]
Oh, thanks ❤🤗

**Pull request merged**
