### PR TITLE
layered button added

### PR DESCRIPTION
**Pull request by angetheo-auth**
added layered button in the animated class

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Thank you @angetheo-auth but you still need to do a few steps:

1. Add `_layered.less` to `src/components/_animated.less`
2. Compile changes with `npm run build`.
3. Add the button to website/src/data/buttons.json

After this commit the changes and they'll appear in this PR. Please follow along the [contributing guidelines](https://github.com/sButtons/sbuttons/blob/master/CONTRIBUTING.md) for more information.

**Review by shahednasser — CHANGES_REQUESTED** [review]
It all looks great @angetheo-auth ! Just one last thing please remove all changes in `website/package-lock.json`. You can copy the content from the main repository to ensure all changes are removed.

**Comment by shahednasser** [comment]
@angetheo-auth  Are you sure you copied the changes from the main repository? Because it keeps showing that there's a conflict between the two files and I can't resolve it.

You can try deleting the file and downloading it from this repository.

**Comment by angetheo-auth** [comment]
i tried deleting the file and downloading it from the main branch but github shows no changes to commit, since i copy pasted the content of it in my last push

**Comment by shahednasser** [comment]
@angetheo-auth Are you copying from your forked repository or this one? Because there has been changes in this one.

**Comment by angetheo-auth** [comment]
i am not copying from my fork

**Comment by shahednasser** [comment]
The only solution here is if we close this PR and you can submit another one.

**Pull request closed without merging**
