### PR TITLE
fixed issue #1378

### PR DESCRIPTION
**Pull request by imkarimkarim**
fixed issue:  Toggle button  not fully visible on Firefox #1378 
sorry for not taking permission to work on this issue. I :eyes:   at the issues and the replies were not fast(at least these days). thanks for your time. happy coding :game_die:

### CODE REVIEW

**Comment by andypants888** [comment]
Hi karim, no problem. I was wondering what you think of the hover pseudo-class that have been changed on the snake buttons? 

This happened to me too... I don't understand why changing the padding from the toggle.less would change the hover pseudo-state.

Thanks.

**Comment by imkarimkarim** [comment]
hi @andypants888 . it got me wondering too. this should be something with less compiler. i don't know much about less... AND we all are learning :) learning never ends :smile:

**Review by shahednasser — CHANGES_REQUESTED** [review]
Hello @imkarimkarim, thank you for your work. Usually, I don't accept pull requests if the issue is already assigned to someone else, but since @andypants888 is ok with it then it's ok.

Your fix works on firefox for input elements, however, you added `margin-left: 10px;` to all toggle button types (not just input elements) that messed up button elements and a elements. Please remove that.

As for the issue you and @andypants888 brought up regarding the snake button, it's definitely strange as it seems that some pull requests have this issue, whereas others don't. Maybe depends on the OS? I'm not sure, but there are two things to note:

1. The compiler's output should be similar to yours, meaning that the `:hover` shouldn't be there.
2. There's a problem with the left and right borders, as they're not showing. I tested it using the CDN as well, and this problem is occurring there too. But, when using the LESS files there's no bug here. Truly strange.

I guess I'll need to open a new issue with this. As for now, please work on the fixes I mention above. Thank you.

**Comment by shahednasser** [comment]
This issue has been fixed by @andypants888 thank you

**Pull request closed without merging**
