### PR TITLE
added footer on Examples page.

### PR DESCRIPTION
**Pull request by AshishRajIITI**

### CODE REVIEW

**Comment by shahednasser** [comment]
Thank you for your work @AshishRajIITI . The sidebar is overlapping with the footer so you need to fix that either by changing the height of the sidebar or change the z-index of the footer.

**Comment by AshishRajIITI** [comment]
Okay, @shahednasser. I will try to fix it up.

**Comment by AshishRajIITI** [comment]
@shahednasser ma'am, I am really sorry. I am not able to fix this this particular issue. :(

**Comment by shahednasser** [comment]
It's ok @AshishRajIITI thank you for your work

**Pull request closed without merging**
