### PR TITLE
Update hinge animation

### PR DESCRIPTION
**Pull request by kalimah-apps**
Hinge is now triggered by hover and adding animated class.

Issue:
https://github.com/sButtons/sbuttons/issues/1022

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Thank you for your contribution @kalimah-apps ! I just need you to run `npm run compile` and commit the changes to be seen on the website.

**Comment by kalimah-apps** [comment]
Hi @shahednasser. I tried to run compile script it changed all files under src, assets and dist folders. I don't think it is a good idea to commit and push all these changes. 
There is an issue with the way npm scripts are setup, particularly with prettier. 

-- This is related but a separate issue
If I run the watch script and change a file it will be stuck in a loop where prettier keeps modifying all files and watch command runs which triggers prettier and so on so forth.

**Comment by shahednasser** [comment]
@kalimah-apps it's fine when you run `git add` command the files commit will be just the ones you actually changed

**Comment by kalimah-apps** [comment]
@shahednasser npm run compile works. Now I am having issue pushing the commit. I tried ssh, https, personal access token and web authentication but keep getting this error:

> remote: Permission to sButtons/sbuttons.git denied to kalimah-apps.
> fatal: unable to access 'https://github.com/sButtons/sbuttons.git/': The requested URL returned error: 403

**Comment by Caleb335** [comment]
Hi @kalimah-apps, 

I think this has to do with your internet connection, kindly check if your internet connection isn't poor

**Comment by shahednasser** [comment]
@kalimah-apps are you pushing the commits directly to this repository? Because you need to push it to your forked repository on the branch you created for this PR.

**Comment by kalimah-apps** [comment]
@shahednasser You are right! 🤦‍♂️

**Comment by shahednasser** [comment]
Hello @kalimah-apps did it work?

**Comment by shahednasser** [comment]
Great work thank you!

@all-contributors please add @kalimah-apps for code

**Pull request merged**
