### PR TITLE
Bubble effect button #568

### PR DESCRIPTION
**Pull request by 3stherMueni**
1. Name of button:
Bubble effect button
2. Description:
After hovering onto button it will change color and small bubbles will come out of it once.
3. Button Type (Animated, Special, etc...):
animated

### CODE REVIEW

**Comment by shahednasser** [comment]
I'm closing this PR as I don't understand what you have done. If you would still like to work on it please submit a PR soon or you will be unassigned. Let me know if you have any questions or require any assistance.

**Comment by 3stherMueni** [comment]
Hello. Thank you for the feedback.  This is my first PR and I kinda have no
idea what exactly i am doing.  Could you kindly explain to me what I did
wrong? I want to understand where i need to correct when in future i make
another PR

**Comment by shahednasser** [comment]
@3stherMueni I think you need to read the [contributing guidelines](https://github.com/sButtons/sbuttons/blob/master/CONTRIBUTING.md) before contributing because it doesn't seem that you have a general understanding of how this repository's structure is like. Once you do and you still have questions or need help let me know.

**Comment by 3stherMueni** [comment]
Thank you. I appreciate the feedback. I will look into the contribution
guidelines.

**Pull request closed without merging**
