### PR TITLE
Adding variables from src files into _variables.less and updating var…

### PR DESCRIPTION
**Pull request by android-lewis**
Hi there,

I added variables from sub src/ less files and updated their variable references

Resolves below issue:

Issue: #804

### CODE REVIEW

**Comment by android-lewis** [comment]
Not sure why the compile step is failing on pull_request and pull_request_target, any insights?

**Comment by shahednasser** [comment]
Hi @android-lewis don't worry about the step. Can you please run `npm run compile`?

**Comment by android-lewis** [comment]
> Hi @android-lewis don't worry about the step. Can you please run `npm run compile`?

Yes no problem will do shortly

**Comment by android-lewis** [comment]
compiled successfully

**Review by shahednasser — CHANGES_REQUESTED** [review]
Can you please add comments to everything from `@neonGreen` and below, not just the variables you moved? Don't forget to compile afterwards.

**Comment by android-lewis** [comment]
No problem yes

**Comment by android-lewis** [comment]
neonGreen etc belong to both _neon.less and _glow.less any input as to what the comment should be, just denote both maybe?

**Comment by HADES-01** [comment]
@android-lewis Yes, denote both so as to remove any ambiguity.

**Comment by android-lewis** [comment]
Updated now

**Comment by android-lewis** [comment]
Compiled successfully also

**Comment by shahednasser** [comment]
Great thank you!

@all-contributors please add @android-lewis for code

**Pull request merged**
