### PR TITLE
A bad try

### PR DESCRIPTION
**Pull request by Sumit2399**
Done
Added Gray color

No,issue
Issue:
This is my first contribution.I am still in the learning phase but don't know much so tried to add Button color.

### CODE REVIEW

**Review by dsnehasish74 — CHANGES_REQUESTED** [review]
Why you delete this buttons-example.js file ??????????????????

**Comment by Sumit2399** [comment]
I am just trying to learn git and open source and I still don't understand all the things.
I made the change where I delete the buttons-examples.js and moved back to the original pull request.

**Comment by shahednasser** [comment]
Hello @Sumit2399 thank you for trying to contribute. We are actually not accepting new button colors at the moment, but if you have any other idea please submit an issue first before working on it. If you need any help you can always ask.

@dsnehasish74 we create a nice environment for beginners in this repo so please make sure you reply nicely to contributors!

Thank you all

**Comment by Sumit2399** [comment]
Ok,I will remember to put a issue first.Thank you for guidance.

**Comment by dsnehasish74** [comment]
@shahednasser  sorry for that I don't want to be rude  😥😥

**Comment by shahednasser** [comment]
It's ok @dsnehasish74 just wanted to point it out!

**Pull request closed without merging**
