### PR TITLE
Have made content in documentation page containered

### PR DESCRIPTION
**Pull request by fleventy-5**
Have made content in documentation page containered

Issue: #1243

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Hello @fleventy-5 thank you for work. Not the entire content should be containered, only the column that includes the content of the documentation (column next to the sidebar one).

Also, you removed a script for carbon ads on line 110 so please add it again.

**Comment by fleventy-5** [comment]
@shahednasser  I'm very sory for my mistake :) should I include the heading h1 "_Get  started with sbuttons "_ also inside the div container or should I create the div container after the heading

**Comment by shahednasser** [comment]
No problem @fleventy-5 ! Yes, include the heading as well. All of the content next to the sidebar should be in the container

**Comment by fleventy-5** [comment]
@shahednasser  can you review my changes. Please tell me if I need to do any other changes.Thanks

**Comment by shahednasser** [comment]
Great work again thanks!

@all-contributors please add @fleventy-5 for documentation

**Comment by fleventy-5** [comment]
@shahednasser  thank you  for your help.

**Pull request merged**
