### PR TITLE
NPM links added #742

### PR DESCRIPTION
**Pull request by crew-guy**
Have rewritten all the code for this in a fresh branch as suggested in #769

### CODE REVIEW

**Comment by crew-guy** [comment]
@shahednasser You were so so right. It was the "format on save" feature in my VSCode creating a format issue

**Review by shahednasser — CHANGES_REQUESTED** [review]
All looks good but please remove all changes in `dist/sbuttons.css` and `src/sbuttons.less`

**Comment by crew-guy** [comment]
> All looks good but please remove all changes in `dist/sbuttons.css` and `src/sbuttons.less`

Done !

**Comment by shahednasser** [comment]
There are still changes in the files I mentioned. Can you just copy them from this repository and paste them in yours?

**Comment by crew-guy** [comment]
> There are still changes in the files I mentioned. Can you just copy them from this repository and paste them in yours?

Yeah sure. I really don't understand why this still keeps happening but I'll look into solving this issue and it's cause to prevent any such mistakes in the future 😄

**Comment by shahednasser** [comment]
There are still some changes in the files that shouldn't have changes in them like `dist/sbuttons.css`. As you are having trouble fixing this, please create a new branch again and submit a new PR. sorry for the inconvenience.

**Comment by crew-guy** [comment]
> There are still some changes in the files that shouldn't have changes in them like `dist/sbuttons.css`. As you are having trouble fixing this, please create a new branch again and submit a new PR. sorry for the inconvenience.

Sure. I'll do it !

**Pull request closed without merging**
