### PR TITLE
Grammatically updated the subtitle in index.html

### PR DESCRIPTION
**Pull request by drewren25**
I made a grammatical change as well as a change in word choice for the subtitle in index.html. Originally it said "Simple buttons you can use easily for your next project." and I changed it to "Easy to use buttons you can use for your next project!"
I found it a bit wonky to read with both "simple" and "easily" in the same sentence so I changed it to just say "easy to use" which I found more concise without losing the original meaning.
I also added an exclamation mark to add a bit of enthusiasm on our part as well as try to instill some into possible users. I was choosing between an exclamation mark and just using no punctuation at all, but I just thought a period was too stern and emotionless for something that I think deserves excitement.

### CODE REVIEW

**Comment by shahednasser** [comment]
I see what you mean. How about we use Simple instead of Easy?

**Comment by drewren25** [comment]
> I see what you mean. How about we use Simple instead of Easy?

Sounds good to me!

**Comment by drewren25** [comment]
Sorry this is my first time working on an open source project like this, does that mean I should make that edit?

**Comment by shahednasser** [comment]
No problem! Yes you should make the changes in your branch then commit the changes, it will update this PR automatically.

**Comment by drewren25** [comment]
> No problem! Yes you should make the changes in your branch then commit the changes, it will update this PR automatically.

Oh ok I see, I'll do that by the end of today(pst)!

**Comment by drewren25** [comment]
Just sent in the commit, is this what you were looking for?

**Comment by shahednasser** [comment]
After looking into this more I think we should keep the current subtitle. I appreciate your contribution and I'll label this as "hacktoberfest-accepted". Thank you.

**Comment by drewren25** [comment]
No problem, thanks for helping me make my first contribution! One more question, since this pr is closed github asks if I want to delete this branch and/or delete this fork. Should I?

**Comment by shahednasser** [comment]
@drewren25 sure you don't need it anymore.

**Pull request closed without merging**
