### PR TITLE
added 3d flip checkbox button

### PR DESCRIPTION
**Pull request by Anshu-jindal**
I have added code for 3d flip checkbox button

Issue: Added a new button in the repository named "3d flip checkbox" under type: "Special"

### CODE REVIEW

**Comment by shahednasser** [comment]
Thank you @Anshu-jindal for your contribution. Unfortunately, the buttons we implement rely on only using one HTML element (usually `<button>`) with the classes we create. You can use pseudo elements like `:before` and `:after`, but that's it. You can refer to how that is with all the other buttons. 

So, you need to change the button to only need one class and not rely on container elements or children elements.

**Comment by Anshu-jindal** [comment]
Okay, I will update my code and will pull the request after doing the required changes

**Comment by Anshu-jindal** [comment]
I am sorry, but I am unable to convert HTML/CSS code into less code such that one CSS class can perform this feature alone. If anyone can help then maybe I will be able to do this but it is difficult for me to do it alone.

**Comment by shahednasser** [comment]
It's ok @Anshu-jindal . I'll close the PR and the issue. thank you for your work.

**Pull request closed without merging**
