### PR TITLE
Resolved sidebar issue when footer is reached

### PR DESCRIPTION
**Pull request by VinayakChopra**
The pull request adds a function to hide the sidebar when the footer becomes visible.
Before fix: https://user-images.githubusercontent.com/43726619/99625119-89f42e00-2a55-11eb-9b85-7b58c7b3c992.png
After fix: https://user-images.githubusercontent.com/43726619/99625114-8791d400-2a55-11eb-9bd4-1021b44d053f.png
As a result of the given function, the site looks much cleaner on reaching the footer than before.

Issue: Enhance sidebar behavior when reaching footer #1012

### CODE REVIEW

**Comment by shahednasser** [comment]
I like the fix but it doesn't work well on small devices. Can you make sure the function only runs when the width of the screen is greater than or equal to 992px?

**Comment by VinayakChopra** [comment]
Hi, @shahednasser  I have added the required media query to the function.

**Comment by VinayakChopra** [comment]
Hi, @shahednasser thanks for the feedback. I have started working on the same, I approached it with a basic media query, which worked but broke a few things. I'll make a commit after fixing the same.

**Comment by shahednasser** [comment]
Hello @VinayakChopra any update on this?

**Comment by VinayakChopra** [comment]
Hi @shahednasser  sorry for being late. I don't have a solution yet I'll reopen this PR if I can solve it.

**Comment by shahednasser** [comment]
No worries @VinayakChopra thank you for letting me know.

**Pull request closed without merging**
