### PR TITLE
Shadow buttons

### PR DESCRIPTION
**Pull request by badhri17**
Issue: #1627

### CODE REVIEW

**Comment by badhri17** [comment]
why closed without merging?

**Comment by shahednasser** [comment]
Thank you for your work @badhri17 and sorry for the delay in merging!

**Comment by badhri17** [comment]
@shahednasser no problem shahaed 👍, please don`t forget to add me to the https://github.com/sButtons/sbuttons/blob/master/CONTRIBUTORS.md

**Comment by shahednasser** [comment]
@all-contributors please add @badhri17 for code

**Pull request merged**
