### PR TITLE
Sidebar on small devices #1161

### PR DESCRIPTION
**Pull request by JithinAji**
Sidebar on small devices. To correct Sidebar on small devices between screen widths 991px and 451px.

Issue:#1161

### CODE REVIEW

**Comment by shahednasser** [comment]
It all looks great, however you have some unnecessary changes due to the fact that your forked repository is behind this one. Can you remove the changes in the unnecessary files?

**Comment by JithinAji** [comment]
Can you check if this is OK.

**Comment by shahednasser** [comment]
Yes great work thanks @JithinAji !

**Comment by nobiaya** [comment]
@JithinAji can i contribute to this project

**Pull request merged**
