### PR TITLE
Added JSDoc for the buttons list objects

### PR DESCRIPTION
**Pull request by HADES-01**
Added JSDoc documentation to buttons list object

Issue: #480

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Looks great but can you also add which properties are optional and what the default would be? Everything but type and label is optional.

**Comment by HADES-01** [comment]
@shahednasser Isn't classes a required property ??

**Comment by shahednasser** [comment]
@HADES-01 no it's not. For example, Animated can work without the classes property.

**Comment by HADES-01** [comment]
@shahednasser Actually according to the jsDocs conventions properties with `[ ]` are considered optional but I can write it out as well if you'd like and what should be default for classes, variations and children

**Comment by shahednasser** [comment]
Yes I think it's best to include it as some people may not know that. 

These properties at the moment don't have a default value so don't add it for them.

**Comment by shahednasser** [comment]
Amazing thanks!

**Pull request merged**
