### PR TITLE
Hatch CSS hover effect parent referencing fixes

### PR DESCRIPTION
**Pull request by Mayank-MP05**
## Bug on [Hatch Icon Page](https://sbuttons.netlify.app/examples#hatch)
_Before_
pre1
pre2
CSS Fixes Added in `_hatch.less` regarding the same.
_After_

Issue: #1424

### CODE REVIEW

**Comment by Mayank-MP05** [comment]
Hey @shahednasser can you please check this PR #1430

**Review by shahednasser — CHANGES_REQUESTED** [review]
Hi @Mayank-MP05 thank you for your contribution. Can you please run `npm run compile` then commit the changes?

**Comment by Mayank-MP05** [comment]
> Can you please run `npm run compile` then commit the change

Yeah Sure Give me a min

**Comment by Mayank-MP05** [comment]
Added New Pull Req @shahednasser Do check it out

**Comment by Mayank-MP05** [comment]
Hey @shahednasser I have done the requested changes can you please the PR #1430 and hence the respective issue

**Comment by shahednasser** [comment]
Thank you for the great work!

@all-contributors please add @Mayank-MP05 for code and bug

**Pull request merged**
