### PR TITLE
New "Login with VK" button. Yay!

### PR DESCRIPTION
**Pull request by AskJag07**
Issue:

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Hi @AskJag07 looks good! My only concern is that there is not "Login with Paypal" functionality so maybe change the text to "Pay with paypal".

**Comment by AskJag07** [comment]
Sure! I’ll work on it as soon as possible. No worries!

**Comment by AskJag07** [comment]
@shahednasser 
#4
Done! Changed "Login with Paypal" to "Pay with Paypal". Ready to merge!

**Review by shahednasser — CHANGES_REQUESTED** [review]
It all looks great, but my final request is placing these buttons in `buttons-examples.js` in the correct alphabetical order under Social.

**Comment by AskJag07** [comment]
Sure!

**Comment by AskJag07** [comment]
I just finished it and sent a pull request.

**Pull request closed without merging**
