### PR TITLE
changed values of both box-shadows...

### PR DESCRIPTION
**Pull request by sawantvikram**
changed box-shadow to 1px 2px 5px and 0px 4px 50px  respectively. is it ok or changes are needed still???

Issue:

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Hello thank you for your work. In order to see the changes on the website, please run `npm run compile` then commit the changes

**Comment by sawantvikram** [comment]
> Hello thank you for your work. In order to see the changes on the website, please run `npm run compile` then commit the changes

mam, please can you tell me how to do npm run compile as I am new to this domain, please can you help me??

**Comment by shahednasser** [comment]
Sorry for the delay @sawantvikram . You first need to run `npm install` in your command line or terminal for all the dependencies in `package.json` to install. Then, you need to run `npm run compile` and all the changes you make in the `.less` files will be reflected in `dist/sbuttons.css`

**Comment by sawantvikram** [comment]
mam I have done as per you said now what to do front as I have compiled it??

**Comment by shahednasser** [comment]
@sawantvikram after compiling it you need to commit the code so that it appears in this pull request

**Comment by shahednasser** [comment]
@sawantvikram any update on this?

**Comment by sawantvikram** [comment]
yes mam sorry for delay

**Comment by shahednasser** [comment]
@sawantvikram it's fine just let me know if you're still working on this or not

**Pull request closed without merging**
