### PR TITLE
navbar_improvements by hussein-hub

### PR DESCRIPTION
**Pull request by hussein-hub**
1. changes in the navbar animation.

Issue: abrupt display of navbar .

### CODE REVIEW

**Comment by shahednasser** [comment]
@hussein-hub Thank you for working on it but as I mentioned in the issue this is in the work!

**Comment by hussein-hub** [comment]
Layout fixes did not include navbar fixes?

**Comment by shahednasser** [comment]
@hussein-hub if you refer back to the issue I said you can work on the shine button. Sorry for any confusion

**Comment by hussein-hub** [comment]
Ok will push changes soon

**Pull request closed without merging**
