### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by medhavisinha**
Issue: The issue was in the index.html file, and it has been resolved; please look at the same and let me know.

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Hi @medhavisinha thank you for your work, but that's not the fix we're looking for. We need to change the value for the `description` meta tag to be something that explains the project more. You can get the content from the landing page or from the documentation. Something descriptive.

**Comment by medhavisinha** [comment]
@shahednasser ah, okay. Got you. i'll add description of the project and get it done. thank you for guiding and keeping patience!

**Comment by mayankmohak** [comment]
is this issue still to be resolved can you please link the respective isuue.

**Comment by shahednasser** [comment]
@medhavisinha are you still working on this?

**Comment by medhavisinha** [comment]
@shahednasser yes, i am. give me four days' time. i've my end semester exams going on. sorry for the delay.

**Comment by shahednasser** [comment]
Hello @medhavisinha I have unassigned you due to inactivity and will be closing this PR. @mayankmohak if you want to work on this please comment on the issue to be assigned.

**Pull request closed without merging**
