### PR TITLE
dropDown button Added

### PR DESCRIPTION
**Pull request by VishakhaAwasthi01**
Issue:

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Hi @VishakhaAwasthi01 thank you for your contribution! Can you please move this button to Icon button and place it in the correct alphabetical order? Thank you!

**Comment by shahednasser** [comment]
@VishakhaAwasthi01 can you please delete sbuttons.min.css as we don't have that anymore?

**Comment by VishakhaAwasthi01** [comment]
the whole file or just my part?

**Comment by shahednasser** [comment]
the whole file

**Comment by shahednasser** [comment]
I'm sorry @VishakhaAwasthi01 I'm trying to resolve the conflicts but they are too many. Can you please update your repo to the latest changes or refork it, add your changes to it then create a new PR?

I'm closing this now awaiting the new PR!

**Pull request closed without merging**
