### PR TITLE
Toggle button visibility firefox fixed #1378

### LINKED ISSUE #1378: Toggle button not fully visible on Firefox
Hi! I'm Andrew and I'm new to contributing and coding in general so please let me know if I have missed some obvious or common detail. Thank you. 

1. Bug description below:

**When using the toggle button feature on Mozilla Firefox, the toggle button is partly hidden along the left/right padding at page-load. Once the user clicks on the toggle button, the full button becomes visible.** 

- Partly hidden - Firefox 87 (desktop)
- Partly hidden - Firefox 88 (android)
- Normal - Brave (android)
- Normal - Chrome (android & desktop)

2. Expected Behavior:

The toggle initial view should be same on both Firefox and Chrome.

3. Screenshots:

Here is a JS Fiddle showing the problem: [LINK](https://jsfiddle.net/uL950jgd/2/)

Overview:
toggle_bug_screenshot

While inspecting element:
image

4. Additional:

I tried setting the padding from 10px to 0px (in the css input), but this caused the white middle button to be incorrectly positioned. 

I am thinking maybe the way to fix this is to look in the .less file, adjust the padding rules for the "input checkbox", adjust the white button animations, recompile, and test in various browsers.

Do you guys have any thoughts? Or opinions on how to approach this?

I'd like to work on this, but not cause extra problems... this would be my first real contribution to any project.

### PR DESCRIPTION
**Pull request by andypants888**
Hi Shahed, this is my proposed fix for issue #1378 .

I ran tests on my end, but please let me know if I have any mistakes in the code.

As for the hover: issue in pull requests, I was previously using Windows 10, build 19043 which caused problems with prettier AND the lessc.

I redid the same changes on Ubuntu 20.04 and there seemed to be no problem. I think you were right about the OS having an effect.

Thanks for all the input! This project has been very valuable for a beginner like me.

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Great work @andypants888 , can you remove link 11 in `src/components/special/_toggle.less`? This one was added from before but this is causing the button to do some sort of effect on page load. Please remove it and run compile again.

**Comment by andypants888** [comment]
> Great work @andypants888 , can you remove link 11 in `src/components/special/_toggle.less`? This one was added from before but this is causing the button to do some sort of effect on page load. Please remove it and run compile again.

Quick question: Can you clarify what is link 11? I'm looking at the toggle.less and I don't understand what it is.

**Comment by shahednasser** [comment]
@andypants888 i'm sorry I meant line 11. Sorry for the confusion

**Comment by andypants888** [comment]
No worries. I removed line 11.

**Comment by shahednasser** [comment]
Thank you for your work!

@all-contributors please add @andypants888 for code and bug

**Pull request merged**
