### PR TITLE
Standardized the Font of Headings in 'getStarted.html'

### PR DESCRIPTION
**Pull request by MorganGodden**
Moved some headings and buttons outside of redundant .text divs. Resulting in correct application of fonts.

Issue: #890

### CODE REVIEW

**Comment by shahednasser** [comment]
Great work thank you!

@all-contributors please add @MorganGodden for code and bug

**Comment by MorganGodden** [comment]
> Great work thank you!
> 
> @all-contributors please add @MorganGodden for code and bug

Thank you :]
And I'm sorry for the issue with the last PR - I am new to this...

**Comment by MorganGodden** [comment]
Oh wonderful...

**Comment by shahednasser** [comment]
@MorganGodden it's ok don't worry about it! Hope you keep contributing to this repo and others as well.

**Pull request merged**
