### PR TITLE
formats the code

### PR DESCRIPTION
**Pull request by khanjanSanghavi**
Issue: 
In this 3 files the code was not formatted properly 
 1)  dist/sbuttons.min.css
    2) package-lock.json
         3)package.json

So I formats the code properly so that everyone could read it properly and help other programmers to fix the bug easily 

Hope my efforts will help someone 
And my first contribution ever will be helping this community to grow 

hope you accept it

### CODE REVIEW

**Comment by sanket95droid** [comment]
>How did you format the code in dist.? massive content, help.

**Comment by khanjanSanghavi** [comment]
Hello
I format it through vs code
Glad that you found it helpful

**Comment by shahednasser** [comment]
Again thank you for your work @khanjanSanghavi but these files don't need formatting. `sbuttons.min.css` is a minified version with not formatting of `sbuttons.css`. `sbuttons.css` is formatted accordingly.

**Comment by khanjanSanghavi** [comment]
Thank you for the clarification sir

**Pull request closed without merging**
