### PR TITLE
#1196 radio button not untoggling fixed

### PR DESCRIPTION
**Pull request by Arnab-Bhakta**
Issue:
#1196 

radio button example modified.

### CODE REVIEW

**Comment by shahednasser** [comment]
Looks great but can you either resize the toggle button and make it smaller or position the label base length with the button? just to make it look better. Also instead of "option1" "option2" "option3" add real options like maybe car brands or anything.

**Comment by Arnab-Bhakta** [comment]
What would be approach to resize the buttons?

**Comment by shahednasser** [comment]
@Arnab-Bhakta I think the resizing might require more work, if it's easier just reposition the label

**Comment by Arnab-Bhakta** [comment]
> @Arnab-Bhakta I think the resizing might require more work, if it's easier just reposition the label

Is this fine?
Screenshot (330)
or any other modification?


what should be in the clipboard part? code including the styling or only the core ?

**Comment by shahednasser** [comment]
Yes that looks great. keep the code block as it is.

**Pull request closed without merging**
