### PR TITLE
navbar icons alignment issues fixed

### PR DESCRIPTION
**Pull request by pinkman7009**
Issue: #597 
sbuttonsissue597

Proposed Changes : 
The navbar icons were initially not aligned properly on smaller devices. Now only the dark theme icon is placed on the top right of the navbar and the other icons have been removed as requested. This makes the alignment proper on smaller devices as well.

Files changed : index.html and index.css

### CODE REVIEW

**Comment by shahednasser** [comment]
@pinkman7009 I tested it and the icon is still aligned outside of the navbar. You should try changing the logo size on smaller screens in navbar to make it work.

**Comment by pinkman7009** [comment]
@shahednasser which screen size is not working on?

**Comment by shahednasser** [comment]
375px

**Comment by pinkman7009** [comment]
@shahednasser i am sorry, i didn't check the Get Started page. I only changed the styles for index.html. However for 375px screen width, the icons are aligned at the top right of the navbar for the index page right?

**Comment by shahednasser** [comment]
@pinkman7009 no it isn't. I think using flex for the navbar at small devices and making the logo smaller would help.

**Comment by pinkman7009** [comment]
@shahednasser i posted a screenshot of screen size 375px. it is at the right of the navbar there. but okay i'll try reducing the logo size.

**Pull request closed without merging**
