### PR TITLE
Added link to logo in navbar

### PR DESCRIPTION
**Pull request by akankshast**
Created a link to the homepage at the logo of sButtons in the navbar.
Please let me know if any changes are expected.
Regards,
Akanksha.

### CODE REVIEW

**Comment by shahednasser** [comment]
Hi @akankshast you did a great job but I missed out on something which is that our website is `sbuttons.github.io/sbuttons/` so if we put the URL as `/` it will just take us to `sbuttons.github.io`. Can you please change the URL to just `index.html`?

**Comment by akankshast** [comment]
Sure I'll make the changes ASAP

**Comment by shahednasser** [comment]
Great work thank you!

@all-contributors please add @akankshast for code

**Comment by akankshast** [comment]
Thanks a lot!
sButtons is really cool and would be really helpful for web developers!
Glad to have contributed my tiny share to it.

**Pull request merged**
