### PR TITLE
z-index of scroll-top button 

### PR DESCRIPTION
**Pull request by Fogeinator**
Added `z-index: 20` to main.css
(footer.css had `z-index: 12`)

Issue: #1010

### CODE REVIEW

**Review by glebkema — CHANGES_REQUESTED** [review]
Thank for your contribution and congratulations on the first pull request :)

Note that when working with styles, we edit the `.less` files and compile them using the `npm run compile` command instead of editing the `.css` files directly.

See detailed instructions here:
https://github.com/sButtons/sbuttons/blob/master/CONTRIBUTING.md#instructions

**Comment by shahednasser** [comment]
Thank you @glebkema for your review but I think the file is edited is correct, as the scroll to top button is not related to the buttons in the less files.

@Fogeinator looks good but can you change the color of the scroll to top to something lighter? Because now it doesn't appear on the footer.

**Comment by Fogeinator** [comment]
Oh, sorry I missed these comments - thanks! I will go change it 👍

**Comment by Fogeinator** [comment]
var(--gray-dark)
image

var(--gray)
image

I change it to gray because i thought it looked better 😅 here are some comparisons too 👀

**Comment by glebkema** [comment]
@shahednasser Thanks for the explanation!

**Review by glebkema — APPROVED** [review]

**Comment by shahednasser** [comment]
Awesome thanks!

@all-contributors please add @Fogeinator for code and bug

**Comment by Fogeinator** [comment]
Thanks everyone!

**Pull request merged**
