### PR TITLE
atom btn

### PR DESCRIPTION
**Pull request by harjotkarwal**
Added special button with primary color (used in logo)

Issue:

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Thank you for your work! Instead of making the button's color based on the logo, I think it should be like the rest of the website, having different color schemes. And then it should be placed under animated. That way it will work on the blue button, red button, or any other color.

**Comment by adsingh14** [comment]
Hi @shahednasser !
I was resolving @harjotkarwal commit on my local space (for practice) and pushed it by mistake. What will I do to resolve this ?

**Comment by harjotkarwal** [comment]
Hello ! Why the @adsingh14 replace my code ? I am new to this and checking review feature and then somebody has pushed the code. Is there any way to get this back ?

**Comment by adsingh14** [comment]
Hi !
There's a mistake from my side. I was helping my student (@harjotkarwal) on my system but I pushed his code by mistake. Is there any way to resolve it ?

**Comment by harjotkarwal** [comment]
There's a mistake from my mentor's side. Sir @adsingh14 was teaching me how to resolve changes and I was using his system for practicing. That code was being written by me. Is there any way to resolve it ?

**Pull request closed without merging**
