### PR TITLE
Likebtn branch

### PR DESCRIPTION
**Pull request by richieracoon**
This pull request is implementing a throbbing heart like Button. 
The issue is currently closed but as I mentioned before, I liked to work on it and did it similar to the star-button. 
As described in the issue an animation was added to scale the size and a text-shadow was added to the heart-icon. 
To add dispersing dots afaik a surrounding container would be necessary to contain outcoming dots and position them behind the heart-icon. 
Issue: #225

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Thank you for your work. can you do the following:

1. add `_like.less` to `_icon.less`
2. run `npm run compile`
3. add the new button to the website in `buttons-examples.js` so that we can see how the button looks like

**Comment by richieracoon** [comment]
Dear @shahednasser your I made the changes you requested =)
and thank you for the opportunity to make a contribution to this project!

**Review by shahednasser — CHANGES_REQUESTED** [review]
Amazing work @richieracoon . One last thing I need you to do for me is to add an `.animated` class to the button. We started requiring that for new buttons. Basically, the animated class triggers the same animation the hover would. You can read more about it in the issue #1022 .

Make sure to run `npm run compile` again once you do that and commit the changes.

**Comment by richieracoon** [comment]
Dear @shahednasser,
thank you for your note. I added the animated class to the like-button now and ran npm compile again as you requested.

**Comment by shahednasser** [comment]
Amazing work thanks!

@all-contributors please add @richieracoon for code and idea

**Pull request merged**
