### PR TITLE
Fix to sButton Spelling

### PR DESCRIPTION
**Pull request by sleekyom**
There an issue created to change the spelling of sButton on the example page and this what was fix in this pull request

Issue: https://github.com/sButtons/sbuttons/issues/1021

### CODE REVIEW

**Comment by shahednasser** [comment]
Thank you @sleekyom for your work. I just noticed that this typo is on the index.html and documentation.html. Can you please change it there as well?

**Comment by sleekyom** [comment]
I will correct this as well

**Comment by sleekyom** [comment]
sButton typo fixed in index.html and documentation.html

**Comment by shahednasser** [comment]
Great thank you!

@all-contributors please add @sleekyom for content

**Comment by sleekyom** [comment]
Yay!
Thanks so much

**Pull request merged**
