### PR TITLE
Added toggle button

### PR DESCRIPTION
**Pull request by chelsi-001011**
Issue: #1 
Added a new button. (Toggle)

### CODE REVIEW

**Comment by chelsi-001011** [comment]
@shahednasser  this is the new pull request! please review it

**Comment by shahednasser** [comment]
@chelsi-001011 please run `npm run compile` and commit the changes.

**Comment by shahednasser** [comment]
Amazing work thank you so much!

@all-contributors please add @chelsi-001011 for code and idea

**Comment by adsingh14** [comment]
@shahednasser Toggle button UX is suitable with checkbox not button type. It should be work as single element else there's no use of it practically.

**Comment by shahednasser** [comment]
@adsingh14 if you have any remarks please submit them as new issues. Thank you.

**Pull request merged**
