### PR TITLE
Reduced the gradient button shadow hover and default size

### PR DESCRIPTION
**Pull request by abid1998**
1) Reduced both hover and default size by 2px.

Issue:

### CODE REVIEW

**Comment by TomWBush** [comment]
Please run `npm run compile` to apply the change to the css file according to [CONTRIBUTING.md](https://github.com/sButtons/sbuttons/blob/react-website/CONTRIBUTING.md#instructions).

**Comment by abid1998** [comment]
Hi should i also check in the generated CSS file ? I had ran npm run compile locally but didn't check it in.

**Comment by abid1998** [comment]
@TomWBush checked in the sbuttons.css file.

**Comment by shahednasser** [comment]
Great work thank you!

@all-contributors please add @abid1998 for code

**Pull request merged**
