### PR TITLE
spooky btn

### PR DESCRIPTION
**Pull request by Hyma200**
I added a spooky button to the website. This was my second pull request since my first one failed. I'm not sure why the automatic merge isn't working. Any help appreciated.

Issue: 435

### CODE REVIEW

**Comment by shahednasser** [comment]
Hi @Hyma200 I'm not a big fan of how the button looks to be honest. It's too big and it doesn't look that spooky. Can you please change it up to make it normal size and maybe add something to it to make it more spooky? Thank you.

**Comment by Hyma200** [comment]
Sure! I'll work on it.

**Comment by shahednasser** [comment]
Sorry I'm still not a big fan of the button. I'll label this as "hacktoberfest accepted" so that it counts for hacktoberfest. Thank you!

**Comment by Hyma200** [comment]
Sorry, but thanks for the label!

**Pull request closed without merging**
