### PR TITLE
Removed the double outline button in side nav bar

### PR DESCRIPTION
**Pull request by SARVESHKHANDELWAL**
Removed the repeated outline button from **Button Styles** section in **side navbar**.

**Issue #824** : There are **2 outline button** section in the website . They both are **same** .

### CODE REVIEW

**Review by dsnehasish74 — COMMENTED** [review]
I guess you should maintain the alphabetical order ???? @shahednasser  what you say???🤔

**Comment by SARVESHKHANDELWAL** [comment]
So, should I make a changes according to alphabetical order. And make a new PR.

**Comment by dsnehasish74** [comment]
I think delete the first one and add last one

**Comment by SARVESHKHANDELWAL** [comment]
Ok I will make that changes.

**Comment by shahednasser** [comment]
Yes @dsnehasish74 is right, @SARVESHKHANDELWAL please maintain the alphabetical order.

**Comment by SARVESHKHANDELWAL** [comment]
I will make the required changes, and will make PR for that.

**Pull request closed without merging**
