### PR TITLE
Added 3D Key button

### PR DESCRIPTION
**Pull request by Charu271**
Issue:

### CODE REVIEW

**Comment by Charu271** [comment]
@shahednasser Will these buttons be merged to the repository

**Comment by shahednasser** [comment]
Hi @Charu271 they will soon, there's still a change we need to make but it's dependant on another issue. I'll let you know once we can proceed.

**Comment by Charu271** [comment]
Okay got it

**Comment by shahednasser** [comment]
Thank you for your work!

@all-contributors please add @Charu271 for code

**Pull request merged**
