### PR TITLE
testing minification

### PR DESCRIPTION
**Pull request by mayankmohak**
Working as per pull request #637 

Issue: to make min file of buttons.css

### CODE REVIEW

**Comment by shahednasser** [comment]
Why did you change the action from clean css to that?

**Comment by mayankmohak** [comment]
sorry just trying the modification and i when i was not able to get then i started trying new and it came to this repo.

**Comment by shahednasser** [comment]
Ok I will uncomment the old code and see if it works properly.

**Comment by mayankmohak** [comment]
how can i test whether it is working or not?

**Comment by shahednasser** [comment]
@mayankmohak it's working now on the master branch. It works on pushing to the branch (including merging pull requests).

Thank you!

**Comment by shahednasser** [comment]
@all-contributors please add @mayankmohak for code

**Pull request merged**
