### PR TITLE
Enhance Sidebar Behavior

### PR DESCRIPTION
**Pull request by TomWBush**
Issue: #1012 

I borrowed @VinayakChopra's idea and a portion of his code. I also added the media query that was requested in #1156.

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Looks good I have two comments: 
1. Instead of just disappearing when reaching the footer, maybe we can make it slide out? Or fade out or something.
2. When reaching the footer then resizing the website, the hamburger button doesn't work anymore.

**Comment by TomWBush** [comment]
> Looks good I have two comments:
> 
> 1. Instead of just disappearing when reaching the footer, maybe we can make it slide out? Or fade out or something.
> 2. When reaching the footer then resizing the website, the hamburger button doesn't work anymore.

I have changed the effect from fade to slide. The two issues should be addressed.

**Review by shahednasser — CHANGES_REQUESTED** [review]
There's still an issue when you scroll to the bottom of the page and the sidebar is hidden, when resizing the screen and clicking the hamburger menu it closes instead of opening (even though it's not opened initially) and doesn't open anymore on clicking on the hamburger menu again.

**Comment by TomWBush** [comment]
> There's still an issue when you scroll to the bottom of the page and the sidebar is hidden, when resizing the screen and clicking the hamburger menu it closes instead of opening (even though it's not opened initially) and doesn't open anymore on clicking on the hamburger menu again.

Just realized the bug you are talking about only happens on the documentation page. I was only testing on the example page. I made some fixes, and it should be working on both pages.

**Comment by shahednasser** [comment]
No actually I was testing the examples page but now it's working fine! Please remove the unnecessary comments so I can merge it.

**Comment by TomWBush** [comment]
My bad. Forgot they were there.

**Comment by shahednasser** [comment]
Great work as always thank you!

**Pull request merged**
