### PR TITLE
enhaced bounce animation of Animated buttons

### PR DESCRIPTION
**Pull request by shubh710**
Issue:
https://github.com/sButtons/sbuttons/issues/751

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Looks good but there's a bit of delay before the animation starts, can you fix that?

**Comment by shubh710** [comment]
> Looks good but there's a bit of delay before the animation starts, can y
Sure I'll fix.

> Looks good but there's a bit of delay before the animation starts, can you fix that?

Sure I'll fix.

**Comment by shubh710** [comment]
Hi @shahednasser,
I have tried to rectify the issue can you check experience now and let me know if it is good enough?
Thanks.

**Comment by shahednasser** [comment]
Looks great thank you!

@all-contributors please add @shubh710 for code

**Pull request merged**
