### PR TITLE
Fix alignment for Image in Documentation Page

### PR DESCRIPTION
**Pull request by tnahddisttud**
**Issue:  Fix alignment for Image in Documentation Page**
Code:  
```css
.doc-logo{
  margin-left: 0;
}
```
The image was improperly aligned because of the extra margin on its left.

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Hello @tnahddisttud thank you for your work. I see that you have added the `.doc-logo` class in the css but you didn't add the class in the HTML so the changes are not applied

**Comment by tnahddisttud** [comment]
Yes. And I have created another pull request after adding the class in the documentation.html file. Please check

**Comment by shahednasser** [comment]
@tnahddisttud please include that change in this PR as it is related to the same issue

**Comment by tnahddisttud** [comment]
I am working on it

**Comment by tnahddisttud** [comment]
@shahednasser  Done. Please check

**Review by shahednasser — CHANGES_REQUESTED** [review]
I don't this solution works as the image got larger and is overlapping with the text below. 

I suggest either centering the text next to the image vertically or making the image smaller

**Comment by tnahddisttud** [comment]
@shahednasser I'll make the image smaller.👍🏼

**Comment by tnahddisttud** [comment]
Hello @shahednasser, I have made the required changes. Please review

**Review by shahednasser — CHANGES_REQUESTED** [review]
@tnahddisttud you didn't make the image smaller, the margin you added is making it bigger. Remove the margin first then make it smaller, or align the text next to it center vertically.

**Comment by shahednasser** [comment]
hi @tnahddisttud any updates on this?

**Pull request closed without merging**
