### PR TITLE
add xsmall and xlarge style buttons

### PR DESCRIPTION
**Pull request by RodolfoNei**
Adding new button sizes xsmall and xlarge. This is my first PR ever, so please warn me of any mistakes. Thank you for the opportunity!

Issue: #734

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Please add the new buttons under "Button Styles" in `assets/js/buttons-examples.js` to see them on the website.

**Comment by RodolfoNei** [comment]
Buttons added to the website

**Comment by shahednasser** [comment]
Looks good but why are you not showing rounded buttons for them?

**Comment by RodolfoNei** [comment]
I just totally missed it, sorry. I am trying to fix it now but I'm getting some conflicts, as soon as I figure this out I will commit it.

**Comment by shahednasser** [comment]
Hi @RodolfoNei do you need any help? Please let me know.

**Comment by RodolfoNei** [comment]
I think I accidentally made an unnecessary merge and now I'm lost in the version control. I don't know if I should be fetching and merging from upstream after the first commit or not, If I am working on a new branch does it make any difference?

**Comment by shahednasser** [comment]
@RodolfoNei can you try cloning your repository again and make the changes then committing? If that doesn't work too I think the easy approach is to create a new branch and make the changes in it again then submit a new PR, but try the first solution before you do that.

**Comment by RodolfoNei** [comment]
I made a new commit, I hope it's right.

**Comment by shahednasser** [comment]
Awesome work! Thank you so much!

@all-contributors please add @RodolfoNei for code and idea

**Comment by RodolfoNei** [comment]
Thank you!

**Pull request merged**
