### PR TITLE
gradient

### PR DESCRIPTION
**Pull request by Charu271**
Issue:

### CODE REVIEW

**Comment by shahednasser** [comment]
Hi @Charu271 thank you for your contribution but I'm not a big fan of how it looks. Can you make it something like this instead?
css-gradient-button

**Comment by Charu271** [comment]
Yeah sure. I will do the required changes

**Comment by shahednasser** [comment]
Instead of making the gradient vertical (top to bottom or opposite) can you make it horizontal (left to right)? You can check out some button examples [here](https://gradientbuttons.colorion.co/). 

Also please place the gradient button under Button Styles type. You might not find the type so you'll need to bring your repo up to date with this one. Make sure to move the less file to `src/components/styles/` and import it in `src/components/_styles.less`

**Comment by Charu271** [comment]
I will add the gradient as said. Do I need to add box shadow as suggested before

**Comment by shahednasser** [comment]
@Charu271 yes add the box shadow

**Comment by Charu271** [comment]
@shahednasser I have changed the gradient to left to right. Mam can you please explain about this checks which are done after a pull request.

**Comment by shahednasser** [comment]
It all looks good but you messed up a lot of things in the website due to wrong resolving of conflicts. As this PR is getting messy, I'm gonna have to close it and ask you to either create a new branch after updating your repository to the latest changes or re-fork this repository. Then, you can add your work again to the new branch and submit a PR again. Thank you.

**Comment by Charu271** [comment]
Okay I will fork the repo again and add my work. Thanks for clarifying the
issue

**Pull request closed without merging**
